/// Flutter icons My
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My
///      fonts:
///       - asset: fonts/My.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class My {
  My._();

  static const _kFontFam = 'My';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
